services:
  - type: web
    name: reserva-ftic
    runtime: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: reserva-ftic-db
          property: connectionString
      - key: MAILER_DSN
        sync: false
    healthCheckPath: /

databases:
  - name: reserva-ftic-db
    plan: free
    ipAllowList: []
