<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\Migrations\AbstractMigration;

final class Version20261210000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Repair missing reservation status log table';
    }

    public function up(Schema $schema): void
    {
        $platform = $this->connection->getDatabasePlatform();

        if ($platform instanceof PostgreSQLPlatform) {
            $this->addSql(<<<'SQL'
                CREATE TABLE IF NOT EXISTS reservation_status_log (
                    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    reservation_id INT NOT NULL,
                    changed_by_id INT NOT NULL,
                    previous_status VARCHAR(50) NOT NULL,
                    new_status VARCHAR(50) NOT NULL,
                    actor_role_label VARCHAR(30) NOT NULL,
                    action VARCHAR(30) NOT NULL,
                    note TEXT DEFAULT NULL,
                    changed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                    PRIMARY KEY (id),
                    CONSTRAINT FK_31FAF1D3B83297E7 FOREIGN KEY (reservation_id) REFERENCES reservation (id) ON DELETE CASCADE NOT DEFERRABLE,
                    CONSTRAINT FK_31FAF1D3828AD0A0 FOREIGN KEY (changed_by_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE
                )
            SQL);
            $this->addSql('CREATE INDEX IF NOT EXISTS IDX_31FAF1D3B83297E7 ON reservation_status_log (reservation_id)');
            $this->addSql('CREATE INDEX IF NOT EXISTS IDX_31FAF1D3828AD0A0 ON reservation_status_log (changed_by_id)');
            $this->addSql('CREATE INDEX IF NOT EXISTS idx_reservation_status_log_changed_at ON reservation_status_log (changed_at)');

            return;
        }

        $this->addSql(<<<'SQL'
            CREATE TABLE IF NOT EXISTS reservation_status_log (
                id INT AUTO_INCREMENT NOT NULL,
                reservation_id INT NOT NULL,
                changed_by_id INT NOT NULL,
                previous_status VARCHAR(50) NOT NULL,
                new_status VARCHAR(50) NOT NULL,
                actor_role_label VARCHAR(30) NOT NULL,
                action VARCHAR(30) NOT NULL,
                note LONGTEXT DEFAULT NULL,
                changed_at DATETIME NOT NULL,
                INDEX IDX_31FAF1D3B83297E7 (reservation_id),
                INDEX IDX_31FAF1D3828AD0A0 (changed_by_id),
                INDEX idx_reservation_status_log_changed_at (changed_at),
                PRIMARY KEY(id),
                CONSTRAINT FK_31FAF1D3B83297E7 FOREIGN KEY (reservation_id) REFERENCES reservation (id) ON DELETE CASCADE,
                CONSTRAINT FK_31FAF1D3828AD0A0 FOREIGN KEY (changed_by_id) REFERENCES `user` (id) ON DELETE CASCADE
            ) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS reservation_status_log');
    }
}
