<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20261212000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add inbox message attachments';
    }

    public function up(Schema $schema): void
    {
        $platform = $this->connection->getDatabasePlatform();

        if ($platform instanceof PostgreSQLPlatform) {
            $this->addSql('CREATE TABLE IF NOT EXISTS inbox_message_attachment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, message_id INT NOT NULL, original_name VARCHAR(255) NOT NULL, stored_name VARCHAR(255) NOT NULL, storage_path VARCHAR(255) NOT NULL, mime_type VARCHAR(120) NOT NULL, file_size INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
            $this->addSql('CREATE INDEX IF NOT EXISTS IDX_INBOX_MESSAGE_ATTACHMENT_MESSAGE ON inbox_message_attachment (message_id)');
            $this->addSql('ALTER TABLE inbox_message_attachment ADD CONSTRAINT FK_INBOX_MESSAGE_ATTACHMENT_MESSAGE FOREIGN KEY (message_id) REFERENCES inbox_message (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        } else {
            $this->addSql('CREATE TABLE inbox_message_attachment (id INT AUTO_INCREMENT NOT NULL, message_id INT NOT NULL, original_name VARCHAR(255) NOT NULL, stored_name VARCHAR(255) NOT NULL, storage_path VARCHAR(255) NOT NULL, mime_type VARCHAR(120) NOT NULL, file_size INT NOT NULL, created_at DATETIME NOT NULL, INDEX IDX_INBOX_MESSAGE_ATTACHMENT_MESSAGE (message_id), PRIMARY KEY(id))');
            $this->addSql('ALTER TABLE inbox_message_attachment ADD CONSTRAINT FK_INBOX_MESSAGE_ATTACHMENT_MESSAGE FOREIGN KEY (message_id) REFERENCES inbox_message (id) ON DELETE CASCADE');
        }
    }

    public function down(Schema $schema): void
    {
        $platform = $this->connection->getDatabasePlatform();

        if ($platform instanceof PostgreSQLPlatform) {
            $this->addSql('ALTER TABLE inbox_message_attachment DROP CONSTRAINT IF EXISTS FK_INBOX_MESSAGE_ATTACHMENT_MESSAGE');
            $this->addSql('DROP TABLE IF EXISTS inbox_message_attachment');
        } else {
            $this->addSql('DROP TABLE inbox_message_attachment');
        }
    }
}
