<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20261207000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create landing page content table for super-admin-managed public sections';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE landing_page_content (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            hero_title VARCHAR(255) NOT NULL,
            hero_description TEXT NOT NULL,
            hero_image VARCHAR(255) DEFAULT NULL,
            hero_cta_label VARCHAR(100) NOT NULL,
            hero_cta_url VARCHAR(255) NOT NULL,
            offers_title VARCHAR(255) NOT NULL,
            offers_subtitle VARCHAR(255) NOT NULL,
            offers_json TEXT NOT NULL,
            about_title VARCHAR(255) NOT NULL,
            about_subtitle VARCHAR(255) NOT NULL,
            about_image VARCHAR(255) DEFAULT NULL,
            about_paragraphs_json TEXT NOT NULL,
            mission_title VARCHAR(255) NOT NULL,
            mission_subtitle VARCHAR(255) NOT NULL,
            mission_json TEXT NOT NULL,
            faq_title VARCHAR(255) NOT NULL,
            faq_subtitle VARCHAR(255) NOT NULL,
            faq_json TEXT NOT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY(id)
        )');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE landing_page_content');
    }
}
