<?php

declare(strict_types=1);

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Attribute\Route;
use App\Repository\FacilityRepository;
use App\Entity\LandingPageContent;
use App\Service\LandingPageContentService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Response;

class HomeController extends AbstractController
{
    #[Route('/', name: 'app_home')]
    public function index(
        FacilityRepository $facilityRepository,
        EntityManagerInterface $em,
        LandingPageContentService $landingPageContentService,
    ): Response
    {
        if ($this->getUser()) {
            return $this->redirectToRoute('app_dashboard');
        }

        $this->ensureLandingPageSchema($em);
        $facilities = $facilityRepository->findEnabledWithImages();
        $content = $em->getRepository(LandingPageContent::class)->findOneBy([], ['id' => 'ASC']);

        $response = $this->render('home/landing.html.twig', [
            'facilities' => $facilities,
            'landing' => $landingPageContentService->toViewData($content),
        ]);
        $response->setPrivate();
        $response->setMaxAge(0);
        $response->setSharedMaxAge(0);

        return $response;
    }

    private function ensureLandingPageSchema(EntityManagerInterface $em): void
    {
        $connection = $em->getConnection();
        $schemaManager = $connection->createSchemaManager();

        if (!$schemaManager->tablesExist(['landing_page_content'])) {
            $connection->executeStatement("CREATE TABLE landing_page_content (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                hero_title VARCHAR(255) NOT NULL,
                hero_description TEXT NOT NULL,
                hero_image VARCHAR(255) DEFAULT NULL,
                hero_cta_label VARCHAR(100) NOT NULL,
                hero_cta_url VARCHAR(255) NOT NULL,
                offers_title VARCHAR(255) NOT NULL,
                offers_subtitle VARCHAR(255) NOT NULL,
                offers_json TEXT NOT NULL,
                about_title VARCHAR(255) NOT NULL,
                about_subtitle VARCHAR(255) NOT NULL,
                about_image VARCHAR(255) DEFAULT NULL,
                about_paragraphs_json TEXT NOT NULL,
                mission_title VARCHAR(255) NOT NULL,
                mission_subtitle VARCHAR(255) NOT NULL,
                mission_json TEXT NOT NULL,
                faq_title VARCHAR(255) NOT NULL,
                faq_subtitle VARCHAR(255) NOT NULL,
                faq_json TEXT NOT NULL,
                social_section_title VARCHAR(255) NOT NULL DEFAULT 'Follow Us',
                social_section_subtitle VARCHAR(255) NOT NULL DEFAULT 'Stay connected with FTIC on our official social channels',
                contact_section_title VARCHAR(255) NOT NULL DEFAULT 'Contact Us',
                contact_section_subtitle VARCHAR(255) NOT NULL DEFAULT 'Reach us through our official email',
                contact_email VARCHAR(255) NOT NULL DEFAULT 'innovate@fit.edu.ph',
                social_links_json TEXT NOT NULL DEFAULT '[]',
                contact_links_json TEXT NOT NULL DEFAULT '[]',
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )");
            return;
        }

        $connection->executeStatement("ALTER TABLE landing_page_content ADD COLUMN IF NOT EXISTS social_section_title VARCHAR(255) NOT NULL DEFAULT 'Follow Us'");
        $connection->executeStatement("ALTER TABLE landing_page_content ADD COLUMN IF NOT EXISTS social_section_subtitle VARCHAR(255) NOT NULL DEFAULT 'Stay connected with FTIC on our official social channels'");
        $connection->executeStatement("ALTER TABLE landing_page_content ADD COLUMN IF NOT EXISTS contact_section_title VARCHAR(255) NOT NULL DEFAULT 'Contact Us'");
        $connection->executeStatement("ALTER TABLE landing_page_content ADD COLUMN IF NOT EXISTS contact_section_subtitle VARCHAR(255) NOT NULL DEFAULT 'Reach us through our official email'");
        $connection->executeStatement("ALTER TABLE landing_page_content ADD COLUMN IF NOT EXISTS contact_email VARCHAR(255) NOT NULL DEFAULT 'innovate@fit.edu.ph'");
        $connection->executeStatement("ALTER TABLE landing_page_content ADD COLUMN IF NOT EXISTS social_links_json TEXT NOT NULL DEFAULT '[]'");
        $connection->executeStatement("ALTER TABLE landing_page_content ADD COLUMN IF NOT EXISTS contact_links_json TEXT NOT NULL DEFAULT '[]'");
    }
}
