<?php

declare(strict_types=1);

namespace App\Controller;

use App\Entity\LandingPageContent;
use App\Service\LandingPageContentService;
use App\Service\SupabaseStorageService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[Route('/superadmin')]
#[IsGranted('ROLE_SUPER_ADMIN')]
class LandingPageController extends AbstractController
{
    public function __construct(
        private readonly SupabaseStorageService $storageService,
        private readonly LandingPageContentService $landingPageContentService,
    ) {
    }

    #[Route('/landing-page', name: 'admin_landing_page', methods: ['GET', 'POST'])]
    public function index(Request $request, EntityManagerInterface $em): Response
    {
        $this->ensureLandingPageTableExists($em);
        $this->ensureLandingPageColumnsExist($em);
        $content = $this->getOrCreateContent($em);

        if ($request->isMethod('POST')) {
            if (!$this->isCsrfTokenValid('landing_page_content', (string) $request->request->get('_token'))) {
                throw $this->createAccessDeniedException('Invalid CSRF token.');
            }

            $this->updateContentFromRequest($content, $request);
            $em->flush();

            $this->addFlash('success', 'Landing page content updated successfully.');

            return $this->redirectToRoute('admin_landing_page');
        }

        return $this->render('admin/landing_page.html.twig', [
            'landing' => $this->landingPageContentService->toViewData($content),
        ]);
    }

    private function getOrCreateContent(EntityManagerInterface $em): LandingPageContent
    {
        $content = $em->getRepository(LandingPageContent::class)->findOneBy([], ['id' => 'ASC']);
        if ($content instanceof LandingPageContent) {
            return $content;
        }

        $content = new LandingPageContent();
        $this->seedDefaultContent($content);
        $em->persist($content);
        $em->flush();

        return $content;
    }

    private function ensureLandingPageTableExists(EntityManagerInterface $em): void
    {
        $connection = $em->getConnection();
        $schemaManager = $connection->createSchemaManager();

        if ($schemaManager->tablesExist(['landing_page_content'])) {
            return;
        }

        $connection->executeStatement('CREATE TABLE landing_page_content (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            hero_title VARCHAR(255) NOT NULL,
            hero_description TEXT NOT NULL,
            hero_image VARCHAR(255) DEFAULT NULL,
            hero_cta_label VARCHAR(100) NOT NULL,
            hero_cta_url VARCHAR(255) NOT NULL,
            offers_title VARCHAR(255) NOT NULL,
            offers_subtitle VARCHAR(255) NOT NULL,
            offers_json TEXT NOT NULL,
            about_title VARCHAR(255) NOT NULL,
            about_subtitle VARCHAR(255) NOT NULL,
            about_image VARCHAR(255) DEFAULT NULL,
            about_paragraphs_json TEXT NOT NULL,
            mission_title VARCHAR(255) NOT NULL,
            mission_subtitle VARCHAR(255) NOT NULL,
            mission_json TEXT NOT NULL,
            faq_title VARCHAR(255) NOT NULL,
            faq_subtitle VARCHAR(255) NOT NULL,
            faq_json TEXT NOT NULL,
            social_section_title VARCHAR(255) NOT NULL,
            social_section_subtitle VARCHAR(255) NOT NULL,
            contact_section_title VARCHAR(255) NOT NULL,
            contact_section_subtitle VARCHAR(255) NOT NULL,
            contact_email VARCHAR(255) NOT NULL,
            social_links_json TEXT NOT NULL,
            contact_links_json TEXT NOT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY(id)
        )');
        $connection->executeStatement('ALTER TABLE landing_page_content ENABLE ROW LEVEL SECURITY');

        return;
    }

    private function ensureLandingPageColumnsExist(EntityManagerInterface $em): void
    {
        $connection = $em->getConnection();
        $schemaManager = $connection->createSchemaManager();

        if (!$schemaManager->tablesExist(['landing_page_content'])) {
            return;
        }

        $connection->executeStatement("ALTER TABLE landing_page_content ADD COLUMN IF NOT EXISTS social_section_title VARCHAR(255) NOT NULL DEFAULT 'Follow Us'");
        $connection->executeStatement("ALTER TABLE landing_page_content ADD COLUMN IF NOT EXISTS social_section_subtitle VARCHAR(255) NOT NULL DEFAULT 'Stay connected with FTIC on our official social channels'");
        $connection->executeStatement("ALTER TABLE landing_page_content ADD COLUMN IF NOT EXISTS contact_section_title VARCHAR(255) NOT NULL DEFAULT 'Contact Us'");
        $connection->executeStatement("ALTER TABLE landing_page_content ADD COLUMN IF NOT EXISTS contact_section_subtitle VARCHAR(255) NOT NULL DEFAULT 'Reach us through our official email'");
        $connection->executeStatement("ALTER TABLE landing_page_content ADD COLUMN IF NOT EXISTS contact_email VARCHAR(255) NOT NULL DEFAULT 'innovate@fit.edu.ph'");
        $connection->executeStatement("ALTER TABLE landing_page_content ADD COLUMN IF NOT EXISTS social_links_json TEXT NOT NULL DEFAULT '[]'");
        $connection->executeStatement("ALTER TABLE landing_page_content ADD COLUMN IF NOT EXISTS contact_links_json TEXT NOT NULL DEFAULT '[]'");
        $connection->executeStatement('ALTER TABLE landing_page_content ENABLE ROW LEVEL SECURITY');
    }

    private function seedDefaultContent(LandingPageContent $content): void
    {
        $defaults = $this->landingPageContentService->defaults();

        $content
            ->setHeroTitle($defaults['heroTitle'])
            ->setHeroDescription($defaults['heroDescription'])
            ->setHeroImage($defaults['heroImage'])
            ->setHeroCtaLabel($defaults['heroCtaLabel'])
            ->setHeroCtaUrl($defaults['heroCtaUrl'])
            ->setOffersTitle($defaults['offersTitle'])
            ->setOffersSubtitle($defaults['offersSubtitle'])
            ->setOffersJson($this->landingPageContentService->encodeArray($defaults['offers']))
            ->setAboutTitle($defaults['aboutTitle'])
            ->setAboutSubtitle($defaults['aboutSubtitle'])
            ->setAboutImage($defaults['aboutImage'])
            ->setAboutParagraphsJson($this->landingPageContentService->encodeArray($defaults['aboutParagraphs']))
            ->setMissionTitle($defaults['missionTitle'])
            ->setMissionSubtitle($defaults['missionSubtitle'])
            ->setMissionJson($this->landingPageContentService->encodeArray($defaults['missionItems']))
            ->setFaqTitle($defaults['faqTitle'])
            ->setFaqSubtitle($defaults['faqSubtitle'])
            ->setFaqJson($this->landingPageContentService->encodeArray($defaults['faqItems']))
            ->setSocialSectionTitle($defaults['socialSectionTitle'])
            ->setSocialSectionSubtitle($defaults['socialSectionSubtitle'])
            ->setContactSectionTitle($defaults['contactSectionTitle'])
            ->setContactSectionSubtitle($defaults['contactSectionSubtitle'])
            ->setContactEmail($defaults['contactEmail'])
            ->setSocialLinksJson($this->landingPageContentService->encodeArray($defaults['socialLinks']))
            ->setContactLinksJson($this->landingPageContentService->encodeArray($defaults['contactLinks']));
    }

    private function updateContentFromRequest(LandingPageContent $content, Request $request): void
    {
        $content
            ->setHeroTitle($this->trimOrFallback((string) $request->request->get('hero_title'), $content->getHeroTitle()))
            ->setHeroDescription($this->trimOrFallback((string) $request->request->get('hero_description'), $content->getHeroDescription()))
            ->setHeroCtaLabel($this->trimOrFallback((string) $request->request->get('hero_cta_label'), $content->getHeroCtaLabel()))
            ->setHeroCtaUrl($this->trimOrFallback((string) $request->request->get('hero_cta_url'), $content->getHeroCtaUrl()))
            ->setOffersTitle($this->trimOrFallback((string) $request->request->get('offers_title'), $content->getOffersTitle()))
            ->setOffersSubtitle($this->trimOrFallback((string) $request->request->get('offers_subtitle'), $content->getOffersSubtitle()))
            ->setAboutTitle($this->trimOrFallback((string) $request->request->get('about_title'), $content->getAboutTitle()))
            ->setAboutSubtitle($this->trimOrFallback((string) $request->request->get('about_subtitle'), $content->getAboutSubtitle()))
            ->setMissionTitle($this->trimOrFallback((string) $request->request->get('mission_title'), $content->getMissionTitle()))
            ->setMissionSubtitle($this->trimOrFallback((string) $request->request->get('mission_subtitle'), $content->getMissionSubtitle()))
            ->setFaqTitle($this->trimOrFallback((string) $request->request->get('faq_title'), $content->getFaqTitle()))
            ->setFaqSubtitle($this->trimOrFallback((string) $request->request->get('faq_subtitle'), $content->getFaqSubtitle()));

        $heroImage = $this->handleUploadedImage($request->files->get('hero_image_file'), 'landing-page');
        if ($heroImage !== null) {
            $content->setHeroImage($heroImage);
        } else {
            $heroImageUrl = trim((string) $request->request->get('hero_image_url', ''));
            if ($heroImageUrl !== '') {
                $content->setHeroImage($heroImageUrl);
            }
        }

        $aboutImage = $this->handleUploadedImage($request->files->get('about_image_file'), 'landing-page');
        if ($aboutImage !== null) {
            $content->setAboutImage($aboutImage);
        } else {
            $aboutImageUrl = trim((string) $request->request->get('about_image_url', ''));
            if ($aboutImageUrl !== '') {
                $content->setAboutImage($aboutImageUrl);
            }
        }

        $offersInput = $request->request->all('offers');
        $content->setOffersJson($this->landingPageContentService->encodeArray($this->normalizeCards($offersInput, $this->landingPageContentService->defaults()['offers'])));

        $aboutParagraphs = $request->request->all('about_paragraphs');
        $content->setAboutParagraphsJson($this->landingPageContentService->encodeArray($this->normalizeTextList($aboutParagraphs, $this->landingPageContentService->defaults()['aboutParagraphs'])));

        $missionInput = $request->request->all('mission_items');
        $content->setMissionJson($this->landingPageContentService->encodeArray($this->normalizeMissionItems($missionInput, $this->landingPageContentService->defaults()['missionItems'])));

        $faqInput = $request->request->all('faq_items');
        $faqItems = $this->normalizeFaqItems($faqInput, $this->landingPageContentService->defaults()['faqItems']);
        $content->setFaqJson($this->landingPageContentService->encodeArray($faqItems));

        $content
            ->setSocialSectionTitle($this->trimOrFallback((string) $request->request->get('social_section_title'), $content->getSocialSectionTitle()))
            ->setSocialSectionSubtitle($this->trimOrFallback((string) $request->request->get('social_section_subtitle'), $content->getSocialSectionSubtitle()))
            ->setContactSectionTitle($this->trimOrFallback((string) $request->request->get('contact_section_title'), $content->getContactSectionTitle()))
            ->setContactSectionSubtitle($this->trimOrFallback((string) $request->request->get('contact_section_subtitle'), $content->getContactSectionSubtitle()))
            ->setContactEmail($this->normalizeContactEmail((string) $request->request->get('contact_email'), $content->getContactEmail()))
            ->setSocialLinksJson($this->landingPageContentService->encodeArray($this->normalizeSocialLinks(
                $request->request->all('social_links'),
                $this->landingPageContentService->defaults()['socialLinks']
            )))
            ->setContactLinksJson($this->landingPageContentService->encodeArray($this->normalizeContactLinks(
                $request->request->all('contact_links'),
                $this->landingPageContentService->defaults()['contactLinks']
            )));
    }

    private function handleUploadedImage(mixed $uploadedFile, string $folder): ?string
    {
        if (!$uploadedFile instanceof UploadedFile) {
            return null;
        }

        $result = $this->storageService->uploadFile($uploadedFile, $folder);
        if (!($result['success'] ?? false)) {
            $this->addFlash('error', (string) ($result['error'] ?? 'Image upload failed.'));
            return null;
        }

        return (string) ($result['url'] ?? '');
    }

    private function normalizeCards(array $items, array $defaults): array
    {
        $normalized = [];
        foreach (array_values($defaults) as $index => $fallback) {
            $item = is_array($items[$index] ?? null) ? $items[$index] : [];
            $normalized[] = [
                'key' => (string) ($fallback['key'] ?? ('card-' . $index)),
                'title' => $this->trimOrFallback((string) ($item['title'] ?? ''), (string) ($fallback['title'] ?? '')),
                'description' => $this->trimOrFallback((string) ($item['description'] ?? ''), (string) ($fallback['description'] ?? '')),
                'linkLabel' => $this->trimOrFallback((string) ($item['linkLabel'] ?? ''), (string) ($fallback['linkLabel'] ?? 'Read more')),
                'linkUrl' => $this->trimOrFallback((string) ($item['linkUrl'] ?? ''), (string) ($fallback['linkUrl'] ?? '#')),
                'image' => $this->trimOrFallback((string) ($item['image'] ?? ''), (string) ($fallback['image'] ?? '')),
            ];
        }

        return $normalized;
    }

    private function normalizeTextList(array $items, array $defaults): array
    {
        $normalized = [];
        foreach (array_values($items) as $index => $item) {
            $text = trim((string) $item);
            if ($text !== '') {
                $normalized[] = $text;
            }
        }

        if ($normalized === []) {
            return array_values(array_map(static fn ($item) => (string) $item, $defaults));
        }

        return $normalized;
    }

    private function normalizeMissionItems(array $items, array $defaults): array
    {
        $normalized = [];
        foreach (array_values($defaults) as $index => $fallback) {
            $item = is_array($items[$index] ?? null) ? $items[$index] : [];
            $normalized[] = [
                'title' => $this->trimOrFallback((string) ($item['title'] ?? ''), (string) ($fallback['title'] ?? '')),
                'text' => $this->trimOrFallback((string) ($item['text'] ?? ''), (string) ($fallback['text'] ?? '')),
            ];
        }

        return $normalized;
    }

    private function normalizeFaqItems(array $items, array $defaults): array
    {
        $normalized = [];
        foreach ($items as $item) {
            if (!is_array($item)) {
                continue;
            }

            $question = trim((string) ($item['question'] ?? ''));
            $answer = trim((string) ($item['answer'] ?? ''));
            if ($question === '' && $answer === '') {
                continue;
            }

            $normalized[] = [
                'question' => $question,
                'answer' => $answer,
            ];
        }

        if ($normalized === []) {
            return $defaults;
        }

        return $normalized;
    }

    private function normalizeSocialLinks(array $items, array $defaults): array
    {
        return $this->normalizeIndexedLinkItems($items, $defaults, function (array $item, array $fallback): array {
            return [
                'platform' => $this->trimOrFallback((string) ($item['platform'] ?? ''), (string) ($fallback['platform'] ?? '')),
                'url' => $this->trimOrFallback((string) ($item['url'] ?? ''), (string) ($fallback['url'] ?? '')),
            ];
        });
    }

    private function normalizeContactLinks(array $items, array $defaults): array
    {
        return $this->normalizeIndexedLinkItems($items, $defaults, function (array $item, array $fallback): array {
            $label = $this->trimOrFallback((string) ($item['label'] ?? ''), (string) ($fallback['label'] ?? ''));
            $url = $this->trimOrFallback((string) ($item['url'] ?? ''), (string) ($fallback['url'] ?? ''));
            $displayText = $this->trimOrFallback((string) ($item['displayText'] ?? ''), (string) ($fallback['displayText'] ?? ''));

            return [
                'label' => $label,
                'url' => $url,
                'displayText' => $displayText !== '' ? $displayText : $this->deriveDisplayTextFromUrl($url),
            ];
        });
    }

    private function trimOrFallback(string $value, string $fallback): string
    {
        $value = trim($value);
        return $value !== '' ? $value : $fallback;
    }

    private function normalizeContactEmail(string $value, string $fallback): string
    {
        $value = trim(str_replace('_', '', $value));
        return $value !== '' ? $value : $fallback;
    }

    private function normalizeIndexedLinkItems(array $items, array $defaults, \Closure $mapper): array
    {
        $normalized = [];
        $values = array_values($items);

        foreach (array_values($defaults) as $index => $fallback) {
            $item = is_array($values[$index] ?? null) ? $values[$index] : [];
            $normalized[] = $mapper($item, $fallback);
        }

        foreach (array_slice($values, count($defaults)) as $item) {
            if (!is_array($item)) {
                continue;
            }

            $normalized[] = $mapper($item, []);
        }

        return $normalized;
    }

    private function deriveDisplayTextFromUrl(string $url): string
    {
        $url = trim($url);
        if ($url === '') {
            return '';
        }

        return preg_replace('/^(mailto:|tel:|https?:\\/\\/)/i', '', $url) ?? $url;
    }
}
