CREATE TABLE class_schedule (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, schedule_date DATE NOT NULL, day_of_week VARCHAR(20) DEFAULT NULL, start_time TIME(0) WITHOUT TIME ZONE NOT NULL, end_time TIME(0) WITHOUT TIME ZONE NOT NULL, course_code VARCHAR(50) NOT NULL, section VARCHAR(50) DEFAULT NULL, faculty_name VARCHAR(255) DEFAULT NULL, faculty_email VARCHAR(180) DEFAULT NULL, source VARCHAR(255) DEFAULT NULL, import_batch_id VARCHAR(64) DEFAULT NULL, schedule_identifier VARCHAR(64) DEFAULT NULL, is_relocated BOOLEAN DEFAULT false NOT NULL, status VARCHAR(50) DEFAULT NULL, start_date DATE DEFAULT NULL, end_date DATE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, facility_id INT NOT NULL, previous_facility_id INT DEFAULT NULL, faculty_user_id INT DEFAULT NULL, PRIMARY KEY (id));
CREATE INDEX IDX_EEF6DAABA7014910 ON class_schedule (facility_id);
CREATE INDEX IDX_EEF6DAAB15CB427A ON class_schedule (previous_facility_id);
CREATE INDEX IDX_EEF6DAABE67D05CF ON class_schedule (faculty_user_id);
CREATE TABLE class_schedule_notification_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, recipient_email VARCHAR(180) NOT NULL, actor_role_label VARCHAR(30) NOT NULL, channels VARCHAR(30) NOT NULL, message TEXT NOT NULL, email_sent BOOLEAN DEFAULT false NOT NULL, in_app_sent BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, class_schedule_id INT NOT NULL, notified_by_id INT NOT NULL, faculty_user_id INT DEFAULT NULL, previous_facility_id INT DEFAULT NULL, new_facility_id INT DEFAULT NULL, PRIMARY KEY (id));
CREATE INDEX IDX_48B6915C9C650DE3 ON class_schedule_notification_log (class_schedule_id);
CREATE INDEX IDX_48B6915CE97D56E9 ON class_schedule_notification_log (notified_by_id);
CREATE INDEX IDX_48B6915CE67D05CF ON class_schedule_notification_log (faculty_user_id);
CREATE INDEX IDX_48B6915C15CB427A ON class_schedule_notification_log (previous_facility_id);
CREATE INDEX IDX_48B6915C350EF868 ON class_schedule_notification_log (new_facility_id);
CREATE TABLE facility (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, capacity INT NOT NULL, description TEXT DEFAULT NULL, image VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_for_reservation BOOLEAN NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, parent_id INT DEFAULT NULL, PRIMARY KEY (id));
CREATE INDEX IDX_105994B2727ACA70 ON facility (parent_id);
CREATE TABLE facility_image (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, path VARCHAR(255) NOT NULL, caption VARCHAR(255) DEFAULT NULL, position INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, facility_id INT NOT NULL, PRIMARY KEY (id));
CREATE INDEX IDX_96A23835A7014910 ON facility_image (facility_id);
CREATE TABLE facility_schedule_block (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, type VARCHAR(50) NOT NULL, block_date DATE NOT NULL, start_time TIME(0) WITHOUT TIME ZONE NOT NULL, end_time TIME(0) WITHOUT TIME ZONE NOT NULL, source VARCHAR(255) DEFAULT NULL, schedule_identifier VARCHAR(255) DEFAULT NULL, notes TEXT DEFAULT NULL, original_item_type VARCHAR(50) DEFAULT NULL, original_item_id INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, facility_id INT NOT NULL, PRIMARY KEY (id));
CREATE INDEX IDX_F7F766FAA7014910 ON facility_schedule_block (facility_id);
CREATE TABLE mentor_application (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(255) NOT NULL, first_name VARCHAR(100) DEFAULT NULL, middle_name VARCHAR(100) DEFAULT NULL, last_name VARCHAR(100) DEFAULT NULL, program_course VARCHAR(255) DEFAULT NULL, specialization VARCHAR(255) NOT NULL, reason TEXT DEFAULT NULL, current_profession VARCHAR(150) DEFAULT NULL, highest_education VARCHAR(150) DEFAULT NULL, mentoring_public_bio TEXT DEFAULT NULL, availability_time VARCHAR(255) DEFAULT NULL, supporting_documents JSON DEFAULT NULL, status VARCHAR(50) NOT NULL, valid_until TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, admin_note TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, student_id INT NOT NULL, PRIMARY KEY (id));
CREATE INDEX IDX_E001ECD7CB944F1A ON mentor_application (student_id);
CREATE TABLE mentor_availability (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, available_date DATE NOT NULL, start_time TIME(0) WITHOUT TIME ZONE NOT NULL, end_time TIME(0) WITHOUT TIME ZONE NOT NULL, is_booked BOOLEAN NOT NULL, mentor_id INT NOT NULL, PRIMARY KEY (id));
CREATE INDEX IDX_CB274DDFDB403044 ON mentor_availability (mentor_id);
CREATE TABLE mentor_custom_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, message TEXT NOT NULL, status VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, mentor_response TEXT DEFAULT NULL, full_name VARCHAR(255) DEFAULT NULL, department_course VARCHAR(255) DEFAULT NULL, preferred_expertise VARCHAR(255) DEFAULT NULL, preferred_schedule VARCHAR(255) DEFAULT NULL, assigned_mentor_name VARCHAR(255) DEFAULT NULL, assigned_mentor_expertise VARCHAR(255) DEFAULT NULL, available_dates VARCHAR(255) DEFAULT NULL, available_time VARCHAR(255) DEFAULT NULL, meeting_method VARCHAR(50) DEFAULT NULL, admin_instructions TEXT DEFAULT NULL, responded_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, scheduled_date DATE DEFAULT NULL, scheduled_time VARCHAR(50) DEFAULT NULL, meeting_type VARCHAR(50) DEFAULT NULL, meeting_link VARCHAR(500) DEFAULT NULL, meeting_location VARCHAR(255) DEFAULT NULL, facility_id INT DEFAULT NULL, facility_name VARCHAR(255) DEFAULT NULL, facility_reserved_by VARCHAR(50) DEFAULT NULL, student_id INT NOT NULL, mentor_profile_id INT DEFAULT NULL, PRIMARY KEY (id));
CREATE INDEX IDX_6986868CCB944F1A ON mentor_custom_request (student_id);
CREATE INDEX IDX_6986868C92E677D4 ON mentor_custom_request (mentor_profile_id);
CREATE TABLE mentoring_appointment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, scheduled_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(50) NOT NULL, topic TEXT DEFAULT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, student_id INT NOT NULL, mentor_id INT NOT NULL, availability_id INT DEFAULT NULL, PRIMARY KEY (id));
CREATE INDEX IDX_8538E640CB944F1A ON mentoring_appointment (student_id);
CREATE INDEX IDX_8538E640DB403044 ON mentoring_appointment (mentor_id);
CREATE INDEX IDX_8538E64061778466 ON mentoring_appointment (availability_id);
CREATE TABLE mentoring_audit_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, subject_type VARCHAR(30) NOT NULL, subject_id INT DEFAULT NULL, subject_label VARCHAR(120) NOT NULL, action VARCHAR(40) NOT NULL, previous_status VARCHAR(50) DEFAULT NULL, new_status VARCHAR(50) DEFAULT NULL, performed_by_name VARCHAR(60) DEFAULT NULL, performed_by_role VARCHAR(30) DEFAULT NULL, note TEXT DEFAULT NULL, logged_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, performed_by_id INT DEFAULT NULL, PRIMARY KEY (id));
CREATE INDEX IDX_C8A22ECE2E65C292 ON mentoring_audit_log (performed_by_id);
CREATE INDEX idx_mentoring_audit_log_logged_at ON mentoring_audit_log (logged_at);
CREATE TABLE mentor_profile (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, display_name VARCHAR(255) NOT NULL, specialization VARCHAR(255) NOT NULL, bio TEXT DEFAULT NULL, education VARCHAR(255) DEFAULT NULL, availability_days JSON DEFAULT NULL, availability_start VARCHAR(100) DEFAULT NULL, availability_end VARCHAR(100) DEFAULT NULL, engagement_points INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id));
CREATE UNIQUE INDEX UNIQ_185C512AA76ED395 ON mentor_profile (user_id);
CREATE TABLE notifications (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(50) NOT NULL, title VARCHAR(255) NOT NULL, message TEXT NOT NULL, status VARCHAR(20) NOT NULL, is_read BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, reference_id INT DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id));
CREATE INDEX IDX_6000B0D3A76ED395 ON notifications (user_id);
CREATE TABLE research_content (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, type VARCHAR(50) NOT NULL, category VARCHAR(100) NOT NULL, tags VARCHAR(255) DEFAULT NULL, summary TEXT DEFAULT NULL, body TEXT DEFAULT NULL, file_path VARCHAR(255) DEFAULT NULL, embedded_link TEXT DEFAULT NULL, external_link TEXT DEFAULT NULL, visibility VARCHAR(30) NOT NULL, repository_type VARCHAR(100) DEFAULT NULL, authors TEXT DEFAULT NULL, abstract TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, author_id INT NOT NULL, PRIMARY KEY (id));
CREATE INDEX IDX_676B80B3F675F31B ON research_content (author_id);
CREATE TABLE reservation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, event_name VARCHAR(255) DEFAULT NULL, email VARCHAR(255) NOT NULL, contact VARCHAR(20) NOT NULL, reservation_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, reservation_start_time TIME(0) WITHOUT TIME ZONE NOT NULL, reservation_end_time TIME(0) WITHOUT TIME ZONE NOT NULL, capacity INT NOT NULL, purpose TEXT DEFAULT NULL, status VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, rejection_reason VARCHAR(255) DEFAULT NULL, user_id INT NOT NULL, facility_id INT NOT NULL, suggested_facility_id INT DEFAULT NULL, PRIMARY KEY (id));
CREATE INDEX IDX_42C84955A76ED395 ON reservation (user_id);
CREATE INDEX IDX_42C84955A7014910 ON reservation (facility_id);
CREATE INDEX IDX_42C8495568500A62 ON reservation (suggested_facility_id);
CREATE TABLE reservation_status_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, previous_status VARCHAR(50) NOT NULL, new_status VARCHAR(50) NOT NULL, actor_role_label VARCHAR(30) NOT NULL, action VARCHAR(30) NOT NULL, note TEXT DEFAULT NULL, changed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, reservation_id INT NOT NULL, changed_by_id INT NOT NULL, PRIMARY KEY (id));
CREATE INDEX IDX_31FAF1D3B83297E7 ON reservation_status_log (reservation_id);
CREATE INDEX IDX_31FAF1D3828AD0A0 ON reservation_status_log (changed_by_id);
CREATE INDEX idx_reservation_status_log_changed_at ON reservation_status_log (changed_at);
CREATE TABLE specialization (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id));
CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, is_verified BOOLEAN NOT NULL, verification_code VARCHAR(10) DEFAULT NULL, first_name VARCHAR(100) DEFAULT NULL, middle_name VARCHAR(100) DEFAULT NULL, last_name VARCHAR(100) DEFAULT NULL, degree VARCHAR(100) DEFAULT NULL, degree_name VARCHAR(255) DEFAULT NULL, specialization VARCHAR(255) DEFAULT NULL, profile_picture VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id));
CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email);
CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id));
CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id);
ALTER TABLE class_schedule ADD CONSTRAINT FK_EEF6DAABA7014910 FOREIGN KEY (facility_id) REFERENCES facility (id) ON DELETE CASCADE NOT DEFERRABLE;
ALTER TABLE class_schedule ADD CONSTRAINT FK_EEF6DAAB15CB427A FOREIGN KEY (previous_facility_id) REFERENCES facility (id) ON DELETE SET NULL NOT DEFERRABLE;
ALTER TABLE class_schedule ADD CONSTRAINT FK_EEF6DAABE67D05CF FOREIGN KEY (faculty_user_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE;
ALTER TABLE class_schedule_notification_log ADD CONSTRAINT FK_48B6915C9C650DE3 FOREIGN KEY (class_schedule_id) REFERENCES class_schedule (id) ON DELETE CASCADE NOT DEFERRABLE;
ALTER TABLE class_schedule_notification_log ADD CONSTRAINT FK_48B6915CE97D56E9 FOREIGN KEY (notified_by_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE;
ALTER TABLE class_schedule_notification_log ADD CONSTRAINT FK_48B6915CE67D05CF FOREIGN KEY (faculty_user_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE;
ALTER TABLE class_schedule_notification_log ADD CONSTRAINT FK_48B6915C15CB427A FOREIGN KEY (previous_facility_id) REFERENCES facility (id) ON DELETE SET NULL NOT DEFERRABLE;
ALTER TABLE class_schedule_notification_log ADD CONSTRAINT FK_48B6915C350EF868 FOREIGN KEY (new_facility_id) REFERENCES facility (id) ON DELETE SET NULL NOT DEFERRABLE;
ALTER TABLE facility ADD CONSTRAINT FK_105994B2727ACA70 FOREIGN KEY (parent_id) REFERENCES facility (id) ON DELETE CASCADE NOT DEFERRABLE;
ALTER TABLE facility_image ADD CONSTRAINT FK_96A23835A7014910 FOREIGN KEY (facility_id) REFERENCES facility (id) ON DELETE CASCADE NOT DEFERRABLE;
ALTER TABLE facility_schedule_block ADD CONSTRAINT FK_F7F766FAA7014910 FOREIGN KEY (facility_id) REFERENCES facility (id) ON DELETE CASCADE NOT DEFERRABLE;
ALTER TABLE mentor_application ADD CONSTRAINT FK_E001ECD7CB944F1A FOREIGN KEY (student_id) REFERENCES "user" (id) NOT DEFERRABLE;
ALTER TABLE mentor_availability ADD CONSTRAINT FK_CB274DDFDB403044 FOREIGN KEY (mentor_id) REFERENCES mentor_profile (id) NOT DEFERRABLE;
ALTER TABLE mentor_custom_request ADD CONSTRAINT FK_6986868CCB944F1A FOREIGN KEY (student_id) REFERENCES "user" (id) NOT DEFERRABLE;
ALTER TABLE mentor_custom_request ADD CONSTRAINT FK_6986868C92E677D4 FOREIGN KEY (mentor_profile_id) REFERENCES mentor_profile (id) NOT DEFERRABLE;
ALTER TABLE mentoring_appointment ADD CONSTRAINT FK_8538E640CB944F1A FOREIGN KEY (student_id) REFERENCES "user" (id) NOT DEFERRABLE;
ALTER TABLE mentoring_appointment ADD CONSTRAINT FK_8538E640DB403044 FOREIGN KEY (mentor_id) REFERENCES mentor_profile (id) NOT DEFERRABLE;
ALTER TABLE mentoring_appointment ADD CONSTRAINT FK_8538E64061778466 FOREIGN KEY (availability_id) REFERENCES mentor_availability (id) NOT DEFERRABLE;
ALTER TABLE mentoring_audit_log ADD CONSTRAINT FK_C8A22ECE2E65C292 FOREIGN KEY (performed_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE;
ALTER TABLE mentor_profile ADD CONSTRAINT FK_185C512AA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE;
ALTER TABLE notifications ADD CONSTRAINT FK_6000B0D3A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE;
ALTER TABLE research_content ADD CONSTRAINT FK_676B80B3F675F31B FOREIGN KEY (author_id) REFERENCES "user" (id) NOT DEFERRABLE;
ALTER TABLE reservation ADD CONSTRAINT FK_42C84955A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE;
ALTER TABLE reservation ADD CONSTRAINT FK_42C84955A7014910 FOREIGN KEY (facility_id) REFERENCES facility (id) NOT DEFERRABLE;
ALTER TABLE reservation ADD CONSTRAINT FK_42C8495568500A62 FOREIGN KEY (suggested_facility_id) REFERENCES facility (id) NOT DEFERRABLE;
ALTER TABLE reservation_status_log ADD CONSTRAINT FK_31FAF1D3B83297E7 FOREIGN KEY (reservation_id) REFERENCES reservation (id) ON DELETE CASCADE NOT DEFERRABLE;
ALTER TABLE reservation_status_log ADD CONSTRAINT FK_31FAF1D3828AD0A0 FOREIGN KEY (changed_by_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE;

INSERT INTO "user" (id, email, roles, password, is_verified, verification_code, first_name, middle_name, last_name, degree, degree_name, specialization, profile_picture)
VALUES
(1, 'SuperAdmin@feutech.edu.ph', '["ROLE_SUPER_ADMIN", "ROLE_USER"]'::json, '$2y$10$kavRT7C4.meNbM8Pt.Eu5.a5/oSjTQ6wso5qUrx/8X7BpPIpOLRmq', true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(2, 'admin@feutech.edu.ph', '["ROLE_ADMIN"]'::json, '$2y$10$kavRT7C4.meNbM8Pt.Eu5.a5/oSjTQ6wso5qUrx/8X7BpPIpOLRmq', true, NULL, 'Admin', NULL, 'User', NULL, NULL, NULL, NULL),
(3, 'faculty.test@feutech.edu.ph', '["ROLE_FACULTY", "ROLE_USER"]'::json, '$2y$10$v442gQr85NGBS6zxvVX8b.DjPSrhiURe1hKOpOzhz2O2HZkZqaYm6', true, NULL, 'Faculty', NULL, 'Tester', NULL, NULL, NULL, NULL)
ON CONFLICT (email) DO UPDATE SET
roles = EXCLUDED.roles,
password = EXCLUDED.password,
is_verified = EXCLUDED.is_verified,
verification_code = EXCLUDED.verification_code,
first_name = EXCLUDED.first_name,
middle_name = EXCLUDED.middle_name,
last_name = EXCLUDED.last_name,
degree = EXCLUDED.degree,
degree_name = EXCLUDED.degree_name,
specialization = EXCLUDED.specialization,
profile_picture = EXCLUDED.profile_picture;

INSERT INTO facility (name, capacity, description, image, created_at, updated_at, available_for_reservation)
VALUES
('CS Project Room', 48, 'Computer Science Project Room equipped with modern facilities and workstations for collaborative project work.', NULL, NOW(), NOW(), true),
('Discussion Room 3', 6, 'Intimate discussion room perfect for small group meetings and focused discussions.', NULL, NOW(), NOW(), true),
('Discussion Room 4', 8, 'Versatile discussion room suitable for group projects and team collaborations.', NULL, NOW(), NOW(), true),
('Presentation Room 1', 40, 'Professional presentation room with advanced audio-visual equipment for seminars and presentations.', NULL, NOW(), NOW(), true),
('Presentation Room 2', 60, 'Large presentation room designed for major conferences, lectures, and large-scale presentations.', NULL, NOW(), NOW(), true),
('COE Project Room', 48, 'College of Engineering dedicated project room equipped for engineering-related collaborative work.', NULL, NOW(), NOW(), true),
('Lounge Area', 150, 'Spacious lounge area perfect for networking, informal gatherings, and social events.', NULL, NOW(), NOW(), true),
('3D Printing Lab', 20, '3D Printing Laboratory equipped with modern 3D printers for prototyping and design projects.', NULL, NOW(), NOW(), true),
('Lounge 1', 30, 'Lounge Area Section 1 for small group discussions and casual meetings.', NULL, NOW(), NOW(), true),
('Lounge 2', 30, 'Lounge Area Section 2 for collaborative work and relaxation.', NULL, NOW(), NOW(), true),
('Lounge 3', 30, 'Lounge Area Section 3 for study groups and informal gatherings.', NULL, NOW(), NOW(), true),
('Lounge 4', 30, 'Lounge Area Section 4 for networking and social events.', NULL, NOW(), NOW(), true);

UPDATE facility child
SET parent_id = parent.id
FROM facility parent
WHERE parent.name = 'Lounge Area'
AND child.name IN ('Lounge 1', 'Lounge 2', 'Lounge 3', 'Lounge 4')
AND child.parent_id IS NULL;

SELECT setval(pg_get_serial_sequence('"user"', 'id'), COALESCE((SELECT MAX(id) FROM "user"), 1), true);
SELECT setval(pg_get_serial_sequence('facility', 'id'), COALESCE((SELECT MAX(id) FROM facility), 1), true);
